name: GitHub Actions
run-name: ${{ github.actor }} ${{ github.event_name }} on ${{ inputs.deploy_target }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check Laravel tests
        uses: vendor/bin/phpunit

#      - name: Start Docker Compose
#        uses: docker compose up -d

